// This file was auto-generated by prisma-generator-typescript-interfaces

export interface users {
  id: string;
  email: string;
  uid: string;
  created_at: Date;
  updated_at: Date;
  post?: post[];
}

export interface post {
  id: string;
  title: string;
  description: string;
  content: string;
  created_at: Date;
  updated_at: Date;
  created_id: string;
  user?: users;
}
